#!/bin/bash

echo "🚀 Setting up Railway deployment for your backend..."
echo ""
echo "📋 STEPS TO FOLLOW:"
echo ""
echo "1. 🌐 Go to: https://railway.app"
echo "2. 🔐 Login with GitHub"
echo "3. ➕ Click 'New Project'"
echo "4. 📁 Select 'Deploy from GitHub repo'"
echo "5. 🎯 Choose your repository: bondly-glow-main"
echo "6. ⚙️  Configure:"
echo "   - Root Directory: backend"
echo "   - Environment: Node.js (auto-detected)"
echo ""
echo "7. 🔧 Add Environment Variables:"
echo "   - JWT_SECRET = your-super-secret-jwt-key-here-12345"
echo "   - NODE_ENV = production"
echo ""
echo "8. 🗄️  Add Database:"
echo "   - Click 'New' → 'Database' → 'PostgreSQL'"
echo ""
echo "9. 🚀 Deploy and get your URL!"
echo ""
echo "10. 📝 Update frontend with your Railway URL:"
echo "    Edit: src/services/realBackendService.ts"
echo "    Replace: https://your-actual-railway-url.up.railway.app/api"
echo ""
echo "11. 🔄 Push changes and Netlify will auto-deploy!"
echo ""
echo "✅ Your backend will be live and free on Railway!"
