[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "rm -f bun.lockb yarn.lock pnpm-lock.yaml",
  "npm ci --only=production"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "npm start"

[providers]
node = "18"

[detectors]
bun = false
yarn = false
pnpm = false
